version: "3"

services:
  eureka:
    image: eureka-server
    build:
      context: ./EurekaDiscovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
      
  reported-app:
    image: reported-app
    restart: on-failure
    build:
      context: ./Reported
      dockerfile: Dockerfile
    depends_on:
      - eureka
      - mongo-db
    environment:
        - EUREKA_SERVER=http://eureka:8761/eureka
    ports:
      - "9000:9000"

  invoice-service:
    image: reported-invoice-service
    restart: on-failure
    build:
      context: ./ReportedInvoice
      dockerfile: Dockerfile
    depends_on:
      - eureka
      - reported-app
      - mongo-db
    environment:
      - EUREKA_SERVER=http://eureka:8761/eureka
    ports:
      - "8000:8000"
    
  mongo-db:
    container_name: reported-mongodb
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
