version: "3"

services:
  eureka:
    image: eureka-server
    build:
      context: ./EurekaDiscovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
      
  reported-app:
    image: reported-app
    restart: on-failure
    build:
      context: ./Reported
      dockerfile: Dockerfile
    links:
      - mongo-db:app_db
    depends_on:
      - eureka
      - mongo-db
    environment:
        - EUREKA_SERVER=http://eureka:8761/eureka
    ports:
      - "9000:9000"

  invoice-service:
    image: reported-invoice-service
    restart: on-failure
    build:
      context: ./ReportedInvoice
      dockerfile: Dockerfile
    links:
      - mongo-db:app_db
    depends_on:
      - eureka
      - reported-app
      - mongo-db
    environment:
      - EUREKA_SERVER=http://eureka:8761/eureka
    ports:
      - "8000:8000"
      
  logging-service:
    image: reported-logging-service
    restart: on-failure
    build:
      context: ./logging
      dockerfile: Dockerfile
    links:
      - mongo-db:app_db
    depends_on:
      - eureka
      - reported-app
      - mongo-db
    environment:
      - EUREKA_SERVER=http://eureka:8761/eureka
    ports:
      - "7000:1000"
    
  mongo-db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
